Remove channel specific
exoplay/exobot-plugin-voting pull request #1
Opened 2017-01-11 07:58 UTC by jolewine

2017-02-20 18:01 UTC, ajacksified requested changes

2017-02-20 18:01 UTC, ajacksified commented on src/voting.js
> +    console.log(results);
nuke the log

2017-03-25 14:19 UTC, jolewine commented
@ajacksified done

2017-03-31 16:59 UTC, ajacksified approved these changes

2017-04-21 02:52 UTC, merged